config/routes.rb
Patman::Application.routes.draw do

  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :patients, shallow: true do
    resources :treatments
    resources :evaluations
  end
   
  
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match  '/admin',  :to => 'pages#admin'
  match '/support', :to => 'pages#support'
  match '/new_p',    :to => 'patients#new'
  root              :to => "patients#index"

end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id          :integer         not null, primary key
#  f_name      :string(255)
#  s_name      :string(255)
#  dob         :date
#  email       :string(255)
#  mobile_no   :integer
#  landline_no :integer
#  occupation  :string(255)
#  interests   :string(255)
#  gender      :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Patient < ActiveRecord::Base
    
  attr_accessible :f_name, :s_name, :dob, :email,
                  :mobile_no, :landline_no, :occupation,
                  :interests, :gender 

  #has_many  :users,       :through   => :treatments
  has_many  :treatments,  :dependent => :destroy
  has_many  :evaluations, :dependent => :destroy
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  

  validates  :f_name,      :presence  => true,
                           :length    => { :maximum => 50 }  
  validates  :s_name,      :presence  => true,
                           :length    => { :maximum => 50 }
  
  validates  :email,        :format     => { :with => email_regex },
                           :unless => Proc.new { |a| a.email.blank? }
  validate   :dob_old  
  validate   :dob_future 
  validates  :dob,         :presence  => true
  validates  :mobile_no,   :length    => { :in => 7..19 }, 
                            :unless => Proc.new { |a| a.mobile_no.blank? }
  validates  :landline_no, :length    => { :in => 7..19 }, 
                            :unless => Proc.new { |a| a.landline_no.blank? }
  validates  :gender,      :inclusion => { :in => %w(male female) }
  validates  :occupation,  :length    => { :maximum => 200 }
  validates  :interests,   :length    => { :maximum => 200 }
  
  def full_name
    [f_name, s_name].join(' ')
  end
  
  def dob_future
    errors.add(:dob, "Date of birth cannot be in the future")if !dob.blank? and dob.future?
  end 
  
  def dob_old   
    errors.add(:dob, "Patient cannot be over 150 years old")if !dob.blank? and dob < 150.years.ago.to_date
  end
  
 
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
before_filter :authenticate
before_filter :admin_user,   :only => :destroy


  def new
    @patient = Patient.new
    @title   = "New Patient"
  end
  
  def index
    @title = "All patients"
    
    @search = Patient.includes(:treatments).search(params[:search])
    #@patients = @search.all
    
    
    
    @patients = @search.relation.paginate(:page => params[:page], :per_page => 8,
                  :order=> "created_at desc")
                
      if @patients.empty?
      flash.now[:notice] = "No patient found"
    end
   
  end
  
  def show
    @patient = Patient.find(params[:id]) 
    @title = @patient.f_name + " "+ @patient.s_name
    @age = Date.today.year - @patient.dob.year
    @dob = @patient.dob.strftime("%e/%_m/%Y ")
    @start = @patient.created_at.strftime("%e/%_m/%Y ")
    
  end
  
  def create
    @patient = Patient.new(params[:patient])
    if @patient.save
       flash[:success] = "New patient record created!"
      redirect_to @patient
    else
      @title = "New Patient"
      render 'new'
    end
  end
  
  def edit
   @patient = Patient.find(params[:id])
   @title = "Edit patient"
  end
  
  def update
    @patient = Patient.find(params[:id])
    if @patient.update_attributes(params[:patient])
      flash[:success] = "Profile updated."
      redirect_to @patient
    else
      @title = "Edit patient"
      render 'edit'
    end
  end
  
   def destroy
    Patient.find(params[:id]).destroy
    
    flash[:success] = "Patient destroyed."
    redirect_to(patients_path)
    
  end

 private
    
    def authenticate
      deny_access unless signed_in?
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="span-8">
    <div class="field">
      <%= f.label :f_name, "First Name" %><br />
      <%= f.text_field :f_name %>
    </div>

    <div class="field">
       <%= f.label :s_name, "Surname" %><br />
      <%= f.text_field :s_name %>
    </div>
  
    <div class="field">
      <%= f.label :email, "Email Address" %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :dob, "Date of Birth" %><br />
      <%= date_select("patient", "dob", :start_year => Time.now.year,:prompt => 
                      { :day => 'Day', :month => 'Month', 
                      :year => ' Year' },:end_year => Time.now.year-150) %>
    </div> 
  </div>  
 
  <div class="span-8 last">

    <div class="field">
      <%= f.label :mobile_no, "Mobile" %><br /> 
      <%= f.text_field :mobile_no %>
    </div>
  
    <div class="field">
      <%= f.label :landline_no, "Landline" %><br />
      <%= f.text_field :landline_no  %>
    </div>
  
    <div class="field">
      <%= f.label :occupation %><br />
      <%= f.text_field :occupation  %>
    </div>
    
    <div class="field">
      <%= f.label :interests %><br />
      <%= f.text_field :interests  %>
    </div>
  
    <div class="field">
    <%= f.label :gender ,"Male" %>   
    <%= f.radio_button  :gender, :male %>
    <%= f.label :gender ,"Female" %> 
    <%= f.radio_button :gender, :female %>
    </div> 
  </div>
  
    

app/views/patients/_patient.html.erb
<tr>
 
 <td><%= link_to patient.full_name , patient %> </td>
 <td><%= link_to "Edit" , edit_patient_path(patient) %> &nbsp;
  <% if current_user.admin? %>
     <%= link_to "Delete", patient, :method => :delete, :confirm => "You sure?",
      :title => "Delete #{patient.f_name} #{patient.s_name}" %>
  <% end %></td>
 <td>
    <%= link_to "New" , new_patient_treatment_path(patient)%> &nbsp;
    <% unless patient.treatments.blank? %>
      <%= link_to "All" , patient_treatments_path(patient)%> &nbsp;
      <%= link_to "Last",  patient.treatments.last %>&nbsp;
   <% end %>
 </td>
 <td> 
      <%= link_to "New" , new_patient_evaluation_path(patient)%> &nbsp;
      <% unless patient.evaluations.blank? %>
        <%= link_to "All" , patient_evaluations_path(patient)%> &nbsp;
        <%= link_to "Last",  patient.evaluations.last %>&nbsp;
      <% end %>
 </td>
</tr>
  

app/views/patients/_patient_table.html.erb
<tr>
 <td><%= patient.created_at.strftime("%e/%_m/%Y ") %> </td>
 <td><%= link_to patient.full_name , patient %> </td>
 <td><%= link_to "Edit" , edit_patient_path(patient) %> 
  <%= if current_user.admin? %>
    | <%= link_to "Delete", patient, :method => :delete, :confirm => "You sure?",
                        :title => "Delete #{patient.f_name} #{patient.s_name}" %></td>
 <td><%= link_to "Treatments" , patient_treatments_path(patient) %> 
    |<%= link_to "New Treatment" , new_patient_treatment_path(patient) %>  </td>
 
 </tr>
  

app/views/patients/edit.html.erb
<% content_for :sidebar do %>
  <%= render "layouts/nav_patient" %>
<% end %>
<h3>Update <%= @patient.f_name + " " + @patient.s_name %></h3>
 
    <%= form_for(@patient) do |f| %>
    <%= render 'fields', :f => f %>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
    <% end %>
    
   
   

app/views/patients/index.html.erb
<% content_for :sidebar do %>
  <%= render "layouts/nav_main" %>
<% end %>
<h3>Patients <% if @search.f_name_or_s_name_contains.blank? %> :All </h3> 
  <% else %>
    <h4>First or Surname contains " <%= @search.f_name_or_s_name_contains %> " </h4>
  <% end %>
    
</br>
<% unless @patients.empty? %>
<%= will_paginate @patients %>
<table class = "main">
  <tr>
    <th> <%= sort_link @search, :f_name, "First" %>, <%= sort_link @search, :s_name, "Surname" %></th>
    <th>Patient</th>
    <th>Treatment</th>
    <th>Evaluation</th>
  </tr>
    <%= render @patients %>
    </table>
<% end %>

app/views/patients/new.html.erb
<% content_for :sidebar do %>
  <%= render "layouts/nav_main" %>
<% end %>
<h2>New Patient</h2>
 
    <%= form_for(@patient) do |f| %>
    <%= render 'fields', :f => f %>
    <div class="actions">
      <%= f.submit "Create Patient" %>
    </div>
    <% end %>
    
   
   

  

app/views/patients/show.html.erb
<% content_for :sidebar do %>
  <%= render "layouts/nav_patient" %>
<% end %>
<table  summary="Profile information" >
  <tr>
    <td class="main" colspan="2"> 
     
      <h3>
        <%= @patient.full_name %> 
      </h3>
    </td>  
  </tr>
    <tr>
       <td>Treatment history </td>
       <td><%= link_to(pluralize(@patient.treatments.count,  'treatment'), 
                                  patient_treatments_path(@patient)) %> </td>
    </tr>
    <tr>
       <td>Patient aged <%= @age %></td><td> Born <%= @dob %></td>
    </tr>
    <% unless @patient.email.blank? %>
    <tr>
      <td> Email Address</td><td> <%= @patient.email %></td>
    </tr>
    <% end %>
    <tr>
      <td>Mobile: <%= @patient.mobile_no %> </td>
      
      
      <td><% unless @patient.landline_no.blank?  %>
      Landline: <%= @patient.landline_no %>
      <% end %></td>
      </tr>
  <% unless @patient.occupation.blank? %>
    <tr>
      <td>Occupation </td><td> <%= @patient.occupation.humanize %> </td>
    </tr> 
  <% end %>  
  <% unless @patient.interests.blank? %>
    <tr>
      <td>Interests </td><td> <%= @patient.interests %> </td>
    </tr> 
  <% end %>
    <tr>
      <td> Gender: <%= @patient.gender %></td> <td></td>
    </tr>
  <tfoot>
     <tr>
      <td colspan="2">
      Record created <%= time_ago_in_words(@patient.created_at, 
                     include_seconds = false) %> ago </td>
     </tr>
  </tfoot>
</table>