config/routes.rb
Patman::Application.routes.draw do

  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :patients, shallow: true do
    resources :treatments
    resources :evaluations
  end
   
  
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match  '/admin',  :to => 'pages#admin'
  match '/support', :to => 'pages#support'
  match '/new_p',    :to => 'patients#new'
  root              :to => "patients#index"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
     
      <% if signed_in? %>
     <li><%= link_to "Users", users_path %></li>
      
      <li><%= link_to "Patients", patients_path %></li>
      <li><%= link_to "New patient", new_patient_path %></li>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
 <div class="span-3" id="logo">
  <%= link_to logo, root_path %>
  </div>
 <div class="span-20 last" id="id">
   <h4 class="push-14">
     <% if signed_in? %>
       Hello <%=current_user.name %> | <%= link_to "Sign out", signout_path, 
       :method => :delete%> 
    
    <% end %>
   </h4>
 </div>
</header>

app/views/layouts/_nav_evaluation.html.erb
<nav>
  <ul>
    
    <% if signed_in? %>
      <li><%= link_to_unless_current("Patients", patients_path) %></li></br>
      <li><%= link_to_unless_current("New patient", new_patient_path) %></li></br>
    <% end %>
    
    <li><%= link_to_unless_current("Show",  patient_path(@evaluation.patient))%>
    </li></br>
    <li><%= link_to_unless_current("Edit", edit_patient_path(@patient))%> 
    </li></br>
    <% if current_user.admin? %>
      <li><%= link_to "Delete", @patient, :method => :delete, 
         :confirm => "You sure?", :title => "Delete #{@evaluation.patient.f_name} 
         #{@evaluation.patient.s_name}"%> </li></br>
    <% end %>
  <hr/>
  
  <% unless(@evaluation.patient.evaluations).blank? %>
      <li><%= link_to_unless_current("Evaluations", 
                                     patient_evaluations_path(@evaluation.patient))%>
      </li></br>
    <% end %>
    <li><%= link_to_unless_current("New ",
                                   new_patient_evaluation_path(@evaluation.patient))%>
    </li></br>
   <% if(@patient).blank? %>
      <li> <%= link_to_unless_current("Edit ", edit_evaluation_path(@evaluation)) %>
      </li></br>
      <li> <%= link_to_unless_current("Show ", evaluation_path(@evaluation)) %>
      </li></br>
    <% end %>
    <% if current_user.admin? %>
        <li> <%= link_to "Delete", @evaluation, :method => :delete, 
        :confirm => "Are you sure?"%>
    <% end %>
        </li></br>
  <hr/>   
    <% unless(@evaluation.patient.treatments).blank? %>
      <li><%= link_to_unless_current("Treatments", 
                                      patient_treatments_path(@evaluation.patient))%>
      </li></br>
    <% end %>
    <li><%= link_to_unless_current("New Treatment",
                                    new_patient_treatment_path(@evaluation.patient))%>
    </li></br>
   <hr/>  
    
  </ul>
</nav>

app/views/layouts/_nav_main.html.erb
<nav>
  <ul> 
    <% if signed_in? %>
      <li><%= link_to_unless_current("Patients", patients_path) %></li></br>
      <li><%= link_to_unless_current("New patient", new_patient_path) %></li></br>
    <% end %>
  </ul>
</nav>
 

app/views/layouts/_nav_patient.html.erb
<nav>
  <ul>
  
    
    <% if signed_in? %>
      <li><%= link_to_unless_current("Patients", patients_path) %></li></br>
      <li><%= link_to_unless_current("New patient", new_patient_path) %></li></br>
    <% end %>
    
    <li><%= link_to_unless_current("Show",  patient_path(@patient))%>
    </li></br>
    <li><%= link_to_unless_current("Edit", edit_patient_path(@patient))%> 
    </li></br>
    <% if current_user.admin? %>
      <li><%= link_to "Delete", @patient, :method => :delete,
      :confirm =>"Are you sure?" %> </li></br>
    <% end %>
  <hr/> 
    <% unless(@patient.treatments).blank? %>
      <li><%= link_to_unless_current("Treatments",  patient_treatments_path(@patient))%>
      </li></br>
    <% end %>
    <li><%= link_to_unless_current("New Treatment",new_patient_treatment_path(@patient))%>
    </li></br>
  <hr/> 
    <% unless(@patient.evaluations).blank? %>
      <li><%= link_to_unless_current("Evaluations", patient_evaluations_path(@patient))%>
      </li></br>
    <% end %>
    <li><%= link_to_unless_current("New Evaluation",new_patient_evaluation_path(@patient))%>
    
  </ul>
</nav>

app/views/layouts/_nav_treatment.html.erb
<nav>
  <ul>
   <% if signed_in? %>
      <li><%= link_to_unless_current("Patients", patients_path) %></li></br>
      <li><%= link_to_unless_current("New patient", new_patient_path) %></li></br>
    <% end %>
    
    <li><%= link_to_unless_current("Show",  patient_path(@treatment.patient))%>
    </li></br>
    <li><%= link_to_unless_current("Edit", edit_patient_path(@treatment.patient))%> 
    </li></br>
    <% if current_user.admin? %>
      <li><%= link_to "Delete", @treatment, :method => :delete, 
         :confirm => "You sure?", :title => "Delete #{@treatment.patient.f_name} 
         #{@treatment.patient.s_name}"%> </li></br>
    <% end %>
  <hr/>  
    <% unless(@treatment.patient.evaluations).blank? %>
      <li><%= link_to_unless_current("Evaluations", 
                                     patient_evaluations_path(@treatment.patient))%>
      </li></br>
    <% end %>
    <li><%= link_to_unless_current("New Evaluation",
                                   new_patient_evaluation_path(@treatment.patient))%>
    </li></br>
  <hr/>  
    <% unless(@treatment.patient.treatments).blank? %>
      <li><%= link_to_unless_current("Treatments", 
                                     patient_treatments_path(@treatment.patient))%>
      </li></br>
    <% end %>
    <li><%= link_to_unless_current("New ",
                                   new_patient_treatment_path(@treatment.patient))%>
    </li></br>
    <% if(@patient).blank? %>
      <li> <%= link_to_unless_current("Edit ", edit_treatment_path(@treatment)) %>
      </li></br>
      <li> <%= link_to_unless_current("Show ", treatment_path(@treatment)) %>
      </li></br>
      <% if current_user.admin? %>
        <li> <%= link_to "Delete", @treatment, :method => :delete, 
        :confirm => "Are you sure?"%>
        </li></br>
    
      <% end %>
    <% end %>
    
  </ul>
</nav>

app/views/layouts/_navigation.2.erb
<nav>
  <ul>
    <% if signed_in? %>
      <li><%= link_to_unless_current("Users", users_path) %></li></br>
      <li><%= link_to_unless_current("Patients", patients_path) %></li></br>
      <li><%= link_to_unless_current("New patient", new_patient_path) %></li></br>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li></br>
    <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
    <% end %>
  </ul>
</nav>
 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if lt IE 8]><%= stylesheet_link_tag  "vendor-ie",  :media => "screen" %>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    
    <%= stylesheet_link_tag "vendor", :media => "screen" %>
    <%= stylesheet_link_tag "application", :media => "screen" %>
    <%= stylesheet_link_tag "vendor-print", :media => "print" %>
    
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag 'jquery_ujs' %>
    <%= csrf_meta_tag %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  
    <div class="container">
     <div class="span-24" id="head">
       <%= render 'layouts/header' %>
     </div>
     <div class="span-17 " id="content"> 
       <section class="round">
         <% flash.each do |key, value| %>
           <div class="flash <%= key %>"><%= value %></div>
         <% end %>
         <%= yield %>
        </section>
      </div>
      <div class="span-6 last" id="sidebar">
        <section class= "round">
          
          <%= render '/layouts/search_box'%>
          <%= yield :sidebar %>
        </section>
      </div> 
       
      <div id="footer" class="span-17">
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>